# Generated by Django 4.2.3 on 2023-09-08 21:44

import apps.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_created_by_post_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default=None, upload_to=apps.utils.files.upload_to),
        ),
    ]
